spring:
  security:
    oauth2:
      client:
        registration:
          oic:
            client-id: ${OIC_CLIENT_ID}
            client-secret: ${OIC_CLIENT_SECRET}
            authorization-grant-type: client_credentials
            client-authentication-method: client_secret_post
            scope: https://dev-oic-axv6tfhynrdg-hy.integration.ap-hyderabad-1.ocp.oraclecloud.com:443urn:opc:resource:consumer::all
        provider:
          oic:
            token-uri: ${OIC_TOKEN_ENDPOINT}

oic:
  register-url: ${OIC_REGISTER_URL}