spring:
  application:
    name: lms-backend
  jpa:
    open-in-view: false
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

server:
  port: 8080